### ISSUE TITLE
I don't get how to use this library

### ISSUE THREAD

**Issue by danielo515** [KyleAMathews/react-responsive-grid#15]
Hello,

I'm trying to use this library because it's part of the default configuration of gatsby, but I'm unable to figure how to make it work.

For example, with this configuration I expect a grid with two rows of two columns each

```
    <Grid columns={4}>
           <Span columns={2}> Name: </Span> <Span columns={2}> {info.name} </Span>
            <Span columns={2}> Description: </Span>  <Span columns={2}> {info.description} </Span>
      </Grid>
```

Instead what I gut is just a div with one div per row. How is supposed I should use this? Am I missing something? Any css import or something like that.

Also, if you don't mind I would like to know the advantages of using this library over regular flex-box css 

Thanks

**Comment by danielo515** [comment]
Ok,
Making some experiments I got what I wanted. Seems that the column system is not very reliable. I have to leave one column empty if I want all of them to fit on the screen:

```
  <Grid columns={5}>
           <Span columns={1}> Name: </Span> <Span columns={3}> {info.name} </Span>
           <Span columns={1}> Description: </Span>  <Span columns={3}> {info.description} </Span>
  </Grid>
```

As you can see, the grid is 5 columns wide, but I'm only able to use 4

**Comment by KyleAMathews** [comment]
The number of `<Span>` columns has to add up to the number of `<Grid>` columns. So in your second example, your grid has 5 columns but your span columns add up to 8. If you want to stack items, put them all within the same `<Span>`.

**Comment by danielo515** [comment]
Ok, now I see how it works. Probably a misconception from my side. Does this works like bootstrap grid system ? If it is different that may be the source of my confusion

**Comment by KyleAMathews** [comment]
Dunno, haven't used bootstrap in a really long time.
